language: objective-c
#osx_image: xcode8.3
sudo: false

#before_install

#install:

#before_script:

script:
   - xcodebuild clean build -project SlippingNaviController.xcodeproj -scheme SlippingNaviController -destination "platform=iOS Simulator,OS=10.3,name=iPhone 7"


#after_script:

#after_install
